# Generated by Django 3.0.5 on 2020-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='mobileNumber',
            field=models.CharField(max_length=10),
        ),
    ]
